### PR TITLE
UTIL: fix sra iters computation

### LINKED ISSUE #585: UCP allreduce avg post op fail in upstream master
2 separate fails in ucp allreduce in upstream master:

1. In gtest, test_allreduce_avg_order/0.avg_post_op (in which np=15) fails if **either** UCC_TL_UCP_ALLREDUCE_KN_RADIX **or** UCC_TL_UCP_ALLREDUCE_SRA_KN_RADIX are changed from default radix 4 to any of the radices: 2,3,8,9,10,11,12,13,14 (succeeds on radices 4,5,6,7,15). 
cmd:
UCC_TL_SHARP_TUNE=0 UCC_TL_NCCL_TUNE=0 UCX_IB_GPU_DIRECT_RDMA=n ./gtest --gtest_filter=test_allreduce_avg_order/0.avg_post_op

2. In mpitest in test_allreduce, if np=28, op=avg, dtype=float32 and UCC_TL_UCP_REDUCE_AVG_PRE_OP=0 then mpi fails.
cmd:
mpirun -x UCC_TL_SHARP_TUNE=0 -UCC_TL_UCP_TUNE=inf -x UCX_ERROR_SIGNALS=ILL,SEGV,BUS,FPE,ABRT -x UCX_HANDLE_ERRORS=freeze --bind-to core -x UCC_TL_SHM_TUNE=0  -x UCC_TL_UCP_REDUCE_AVG_PRE_OP=0 -np 28 --map-by core ucc_test_mpi --colls allreduce --mtypes host -m 4:4 --onesided 0 -t world --ops avg --dtypes float32

### PR DESCRIPTION
**Pull request by vspetrov**
## What
Fixes "ucc_kn_pattern_pattern_loop_last_iteration". It used to return incorrect value in the case of extra ranks. This causes failure in allreduce after PR #602 . It also fixes #585 

## How ?
Compute n_iters for direct and backward KN pattern. Also change the way step_radix/block_count are computed, based n_full_subtrees.

### CODE REVIEW

File: src/coll_patterns/recursive_knomial.h [hunk 1]
```diff
@@ -39,35 +39,55 @@ enum {
...
     ucc_rank_t     n_extra; /**< number of "extra" ranks to be served by "proxies" */
 } ucc_knomial_pattern_t;
 
+static inline ucc_rank_t ucc_kn_pattern_n_full(ucc_knomial_pattern_t *p)
+{
+    return p->size / p->full_pow_size;
+}
+
+static inline ucc_rank_t ucc_kn_pattern_radix_pow_init(ucc_knomial_pattern_t *p,
+                                                       int backward)
```
Comment (Sergei-Lebedev) [inline src/coll_patterns/recursive_knomial.h:58]: backward argument is not needed, you can use p->backward

**Review by Sergei-Lebedev — APPROVED** [review]

**Comment by vspetrov** [comment]
bot:retest
